
###
# Development environment configuration
##

# Application settings
APP_NAME: '${pkg.name}'
APP_VERSION: '${pkg.version}'
APP_TITLE: 'My Application'

# API settings
API_PORT: 8081
API_BASE_PATH: '/api'

# Authentication settings
AUTH_CLIENT_IDENTIFIER: '${pkg.name}'
