
###
# Production environment configuration
##

# Application settings
APP_NAME: '${pkg.name}'
APP_VERSION: '${pkg.version}'
APP_TITLE: 'My Application'
APP_BASE_URL: 'https://my-application.com'

# API settings
API_BASE_URL: 'https://my-application.com/api/'

# Authentication settings
AUTH_CLIENT_IDENTIFIER: '${pkg.name}'
